### ISSUE TITLE
Feature Request - Create Feature Flag 

### ISSUE THREAD

**Issue by turnerniles** [wyvern8/launchdarkly-nodeutils#98]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you running the correct version of node? (v8.x) 
* [x] Did you perform a cursory search?

### Description

I don't see the ability to create a new feature flag via launch darkly using this tool. Would you accept a PR for it?

**Comment by turnerniles** [comment]
Ok nevermind. I see "This is not the sdk for implementing flags in your app - it is the api to manage your account/flags.".

**Comment by wyvern8** [comment]
completely missed this one - answer is yes.
